package twiner;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author akshay
 */
class Segmentation_screen extends javax.swing.JFrame {

    /**
     * Creates new form Segmentation
     */
    public Segmentation_screen() {
        initComponents();
        setSize(750,450);
        DefaultListModel dlm = null;
        try {
            File input2 = new File("/Users/satishc/Desktop/ProcessedTweets.txt");
            //File input1 = new File("/Users/satishc/Desktop/Segmentation_set.txt");
            File input1 = new File("/Users/satishc/Desktop/processedSegments.txt");

            Scanner scSegRes = new Scanner(input1);
            scSegRes.useDelimiter("\\|");
            
            dlm = new DefaultListModel();
            int count =1;
            while(scSegRes.hasNext())
            {
            Scanner sc1 =new Scanner(scSegRes.next());
            sc1.useDelimiter("\\n");
            dlm.addElement("Tweet "+count+" :\n");
            
            
            while(sc1.hasNext()){
                dlm.addElement(sc1.next()+"\n");
                dlm.addElement("\n");
            }
            count++;
            }
            Scanner sc2 = new Scanner(input2);
            sc2.useDelimiter("\\|");
             
            DefaultListModel dlm1 = new DefaultListModel();
            
            while(sc2.hasNext()){
                dlm1.addElement(sc2.next());
                dlm1.addElement("\n");
            }
            
           
            preprocessed.setModel(dlm1);
            segresult.setModel(dlm);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Preprocessing_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the c
     * Constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        preprocessed = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        segresult = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("              Segmentation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(226, 21, 300, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Preprocessed Tweet");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 72, 165, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Segmented Result");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(403, 73, 160, 40);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("Entity Verification");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(403, 378, 260, 40);

        jScrollPane1.setViewportView(preprocessed);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(25, 112, 311, 251);

        jScrollPane2.setViewportView(segresult);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(403, 112, 320, 250);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(116, 378, 80, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twiner/Background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 750, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JenaConnection jCon = new JenaConnection();
        jCon.verificationOp();
        
        Comparison cmp = new  Comparison();
        setVisible(false);
        cmp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            File input2 = new File("/Users/satishc/Desktop/ProcessedTweets.txt");
            //File input1 = new File("/Users/satishc/Desktop/Segmentation_set.txt");
            File input1 = new File("/Users/satishc/Desktop/processedSegments.txt");

            Scanner sc1 =new Scanner(input1);
            sc1.useDelimiter("\\n");
             
            DefaultListModel dlm = new DefaultListModel();
            
            while(sc1.hasNext()){
                dlm.addElement(sc1.next()+"\n");
                dlm.addElement("\n");
            }
            
            
            Scanner sc2 = new Scanner(input2);
            sc2.useDelimiter("\\|");
             
            DefaultListModel dlm1 = new DefaultListModel();
            
            while(sc2.hasNext()){
                dlm1.addElement(sc2.next());
                dlm1.addElement("\n");
            }
            
           
            preprocessed.setModel(dlm1);
            segresult.setModel(dlm);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Preprocessing_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList preprocessed;
    private javax.swing.JList segresult;
    // End of variables declaration//GEN-END:variables
}
